### ISSUE TITLE
An Sdist that needs to be built can now refer to itself for building

### ISSUE THREAD

**Issue by tdejager** [prefix-dev/rip#114]
# Problem

This causes a recursive problem, as during resolution it tries to build itself again to get the metadata. Most of the time this is not a problem because a suitable wheel exists that we can use to build said Sdist.

However, you can easily reproduce this by changing the resolution in the wheel builder to `SDistOnly` and use `--only-sdists` from the CLI.

E.g: `cargo r flask --only-sdists` this will run into this issue.

# Resolution

What we could do is use an older version to build the current, by excluding the version we are building from the package resolution step. This could potentially move all the way down the dependency chain and we could bootstrap each version of that package. However, this assumes that the lowest version does *not* depend on itself. If the same version as the sdist we are building is the only candidate, then I think we should error.

**Comment by wolfv** [comment]
This is also achieved with #163
