### ISSUE TITLE
Support source dependencies

### ISSUE THREAD

**Issue by baszalmstra** [prefix-dev/rip#119]
Now that we can build wheels from source distributions, it would be really useful to be able to specify source dependencies. E.g.

```
foo = { git="https://github.com/foo-bar/foo.git" }
```

[pep508_rs already supports this in requirements](https://docs.rs/pep508_rs/0.2.3/pep508_rs/enum.VersionOrUrl.html).

**Comment by nichmor** [comment]
Hello!
I would like to ask if this issue is free 😊 
If yes, would it be possible for me to start working on it?

Thank you!

**Comment by wolfv** [comment]
@nichmor to my knowledge, no one is working on it :)

Maybe it would be best to start with local path dependencies?

For `git` dependencies, we could re-use some code we have in `rattler-build` (where we are using `git` from the command line to check out a repository).

**Comment by nichmor** [comment]
@wolfv 
Thank you for the suggestion! 
Will start with local path first
