### ISSUE TITLE
Support authentication for `rip::index::PackageDb`

### ISSUE THREAD

**Issue by vlad-ivanov-name** [prefix-dev/rip#131]
To support custom/private pip registries (https://github.com/prefix-dev/pixi/issues/588), `PackageDb` needs to support authentication.

I would propose the following API:

1) create a trait that lives somewhere near `PackageDb`, e. g. `ProvidesAuth`
2) the trait would include an `authorize` method (does it need to accept request body and headers? at least in case with google cloud it doesn't need to)
3) let clients like pixi implement the trait and pass an instance of an object via `Option<Box<dyn ProvidesAuth>>`

I'm open to other suggestions and feedback on this

**Comment by baszalmstra** [comment]
Im not sure what the authentication scheme looks like for pypi registries but we might be able to reuse [`AuthenticatedClient`](https://docs.rs/rattler_networking/latest/rattler_networking/struct.AuthenticatedClient.html) in `rattler_networking` for this.
