### ISSUE TITLE
[PyPI] platform_system parsing problem

### ISSUE THREAD

**Issue by ismail** [prefix-dev/rip#146]
Reproducer on linux-aarch64:

`pixi.toml`

```
[project]
name = "stats"
channels = ["conda-forge"]
platforms = ["linux-aarch64"]

[dependencies]
python = ">=3.12.*"

[pypi-dependencies]
jupyterlab = '*'
```

```
❯ pixi --version
pixi 0.12.0
```

`pixi install` results in:

```
❯ pixi install
ERROR rattler_installs_packages::types::core_metadata: ignoring Requires-Dist: matplotlib-inline (<0.2.0appnope,>=0.1.0) ; platform_system == "Darwin", failed to parse: Version specifier `<0.2.0appnope` doesn't match PEP 440 rules
matplotlib-inline (<0.2.0appnope,>=0.1.0) ; platform_system == "Darwin"
                   ^^^^^^^^^^^^^
ERROR rattler_installs_packages::types::core_metadata: ignoring Requires-Dist: matplotlib-inline (<0.2.0appnope,>=0.1.0) ; platform_system == "Darwin", failed to parse: Version specifier `<0.2.0appnope` doesn't match PEP 440 rules
matplotlib-inline (<0.2.0appnope,>=0.1.0) ; platform_system == "Darwin"
                   ^^^^^^^^^^^^^
ERROR rattler_installs_packages::types::core_metadata: ignoring Requires-Dist: matplotlib-inline (<0.2.0appnope,>=0.1.0) ; platform_system == "Darwin", failed to parse: Version specifier `<0.2.0appnope` doesn't match PEP 440 rules
matplotlib-inline (<0.2.0appnope,>=0.1.0) ; platform_system == "Darwin"
                   ^^^^^^^^^^^^^
✔ Project in /home/ismail/envs/stats is ready to use!
```

**Comment by notatallshaw** [comment]
FYI, this does indeed look like an invalid version specification to me.  Did the command successfully install?

It would be great if the error message included the parent, i.e. the package which had the requirement with the invalid specifier.

**Comment by ismail** [comment]
The installation looks good to me:

```
❯ ls .pixi/env/lib/python3.12/site-packages/matplotlib_inline*
.pixi/env/lib/python3.12/site-packages/matplotlib_inline:
backend_inline.py  config.py  __init__.py

.pixi/env/lib/python3.12/site-packages/matplotlib_inline-0.1.6.dist-info:
HASH  INSTALLER  LICENSE  METADATA  RECORD  WHEEL  top_level.txt
```

**Comment by ismail** [comment]
This looks like a parser error to me, the line is

```
    "matplotlib-inline>=0.1",
    'appnope;platform_system=="Darwin"',
```

see https://github.com/ipython/ipykernel/blob/main/pyproject.toml#L34C6-L34C13

**Comment by ismail** [comment]
Updated the issue title to reflect the real problem.

**Comment by ismail** [comment]
The issue is not reproducible on macOS, so I'm guessing parsing of `platform_system` do actually work.

**Comment by tdejager** [comment]
Sorry, still don't really understand, is this a valid specification?

```
Requires-Dist: matplotlib-inline (<0.2.0appnope,>=0.1.0) ; platform_system == "Darwin"
```

specifically the `appnope` part?

**Comment by ismail** [comment]
I downloaded https://files.pythonhosted.org/packages/b0/71/348c659f0fbbf526ca77fae9fd31d43a3c90d4d60ae3df6d477055ee90d5/ipykernel-6.28.0-py3-none-any.whl and unpacked it.

`ipykernel-6.28.0/ipykernel-6.28.0.dist-info/METADATA` shows this

```
Requires-Dist: appnope; platform_system == 'Darwin'
```

but if you install with pixi, `METADATA` shows:

```
Requires-Dist: matplotlib-inline (<0.2.0appnope,>=0.1.0) ; platform_system == "Darwin"
```

so there is no `appnope` version specification. There is a bug in rip/pixi mangling the lines together. Again upstream https://github.com/ipython/ipykernel/blob/main/pyproject.toml#L34C6-L34C13 has

```
    "matplotlib-inline>=0.1",
    'appnope;platform_system=="Darwin"',
```

**Comment by wolfv** [comment]
This error comes from a previous ipykernel version (https://github.com/ipython/ipykernel/pull/709)

I think we could do a better job at reporting the error (add the version it comes from). 

I believe pip (and we) just skip over packages with wrong metadata. Not sure if we should show this to the user by default (since they can't change it usually).

**Comment by tdejager** [comment]
> I believe pip (and we) just skip over packages with wrong metadata. Not sure if we should show this to the user by default (since they can't change it usually).

Yeah this is correct, both @baszalmstra and took that behavior from pip.

**Comment by ismail** [comment]
@wolfv Thank you! I guess we can just do an s/ERROR/Warning/ since it was quite confusing as it did install the package.

**Comment by tdejager** [comment]
Yeah, that part does seem a bit strange to me, as it explicitly skips the requirement:

https://github.com/prefix-dev/rip/blob/6faf63a6e76b2981335f4cdd14bac2f4f59cc9b6/crates/rattler_installs_packages/src/types/core_metadata.rs#L88C1-L128C1

So I'm guessing the dependency still comes in somewhere down the line?

**Comment by tdejager** [comment]
Ah, after talking to @wolfv I understand that it is a problem during backtracking, so not really for the package it selected in the end. I think we could make the log a Warning or Debug statement for now. :)
