### ISSUE TITLE
WheelBuilder: use python version as cache key

### ISSUE THREAD

**Issue by tdejager** [prefix-dev/rip#152]
When building wheels with a source distribution, we also need to take the the `PythonVersion` into account when hitting the cache. Currently, we only use the contents of the `sdist`. 

When creating the `WheelKey` we should probably add this to the hash.

Pixi will also need to supply this information later.

@baszalmstra when using this in the content-hash it will not actually be the content, but I don't think we can utilize the `cacache` metadata in this case. We could also associate it with a specific key, WDYT?

**Comment by baszalmstra** [comment]
Yeah you'd need to add the python version as part of the key.

**Comment by baszalmstra** [comment]
Yeah in that case the Python-version needs to be part of the key. So if you would use the shahash as the key previously now it would be something along the lines of:

`<sha>-<python-version>`

You can of course encode anything in the key.

**Comment by tdejager** [comment]
Closed by: #159
