### ISSUE TITLE
Consider making PythonInterpreterVersion public API

### ISSUE THREAD

**Issue by mattem** [prefix-dev/rip#155]
Hi, I'm a maintainer on the Bazel build system, and [rules_py](https://github.com/aspect-build/rules_py).  I'm looking to make use of `VEnv` in the `rattler_installs_packages` crate.

We have a requirement where we are unable to call the Python interpreter to determine its version, however we already know the interpreters version statically ahead of time, but as `PythonInterpreterVersion` isn't public, we can't make use `VEnv::create_pyvenv` to workaround the version interrogation in `VEnv::create_custom`.

What are the thoughts around either moving `PythonInterpreterVersion` to the public API, or providing another function on `VEnv` that takes a version string or tuple?

**Comment by tdejager** [comment]
Sounds good! What would you prefer? Open to both:)

**Comment by mattem** [comment]
I think my preference would be making it public.

**Comment by tdejager** [comment]
Okay, if you want to make a PR go ahead! Otherwise I'll get to it the coming week :)

**Comment by mattem** [comment]
Great! I can put up a PR 👍

**Comment by tdejager** [comment]
Thanks for the PR 😀 !
