### ISSUE TITLE
Spec `pandas[excel]` gets old version of Pandas

### ISSUE THREAD

**Issue by notatallshaw** [prefix-dev/rip#24]
Since 2.0 Pandas have added several optional extras: https://pandas.pydata.org/docs/getting_started/install.html#optional-dependencies

One common one is `pandas[excel]`, but when I try and run rip against this spec I get Pandas 1.5.3 which is before this optional extra was added, no explanation is given:

```
$ cargo r -- pandas[excel]
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/rip 'pandas[excel]'`
Resolved environment:
- pandas[excel]

Name             Version
numpy            1.26.0
pandas[excel]    1.5.3
python-dateutil  2.8.2
pytz             2023.3.post1
six              1.16.0
```

Running pandas without the optional extra gets the expected Pandas version:

```
$ cargo r -- pandas
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/rip pandas`
Resolved environment:
- pandas

Name             Version
numpy            1.26.0
pandas           2.1.1
python-dateutil  2.8.2
pytz             2023.3.post1
six              1.16.0
tzdata           2023.3
```

**Comment by baszalmstra** [comment]
Thats not good! Ill take a look!

**Comment by notatallshaw** [comment]
Thanks, also I think the output message shoud highlight when it failed to get an extra:

The report gives:

```
pandas[excel]    1.5.3
```

But this extra did not exist for 1.5.3, I beleive the spec on this is extras are considered optional, so it's technically correct to be able to install `pandas` without the extra excel even when you specify it (which personally I wish all installers provided an option to override thie behavior and fail to install when the extra isn't present), but at the very least the user should be alerted.

**Comment by baszalmstra** [comment]
After a little investigation, it turns out that this is the same result `pip` returns:

```shell
> pip install pandas[excel] --only-binary :all: --dry-run
...
Would install numpy-1.26.0 pandas-1.5.3 python-dateutil-2.8.2 pytz-2023.3.post1 six-1.16.0
```

We currently don't deal with sdists at all yet (that's why I use `--only-binary :all:`).

When we do consider sdists with pip we get the result you'd expect:

```shell
> pip install pandas[excel] --dry-run
...
Would install XlsxWriter-3.1.5 defusedxml-0.7.1 et-xmlfile-1.1.0 numpy-1.26.0 odfpy-1.4.1 openpyxl-3.1.2 pandas-2.1.1 python-dateutil-2.8.2 pytz-2023.3.post1 pyxlsb-1.0.10 six-1.16.0 tzdata-2023.3 xlrd-2.0.1
```

I see your point with regard to the report being incorrect. Pip indeed prints a warning:

```
WARNING: pandas 1.5.3 does not provide the extra 'excel'
```

I will add a warning to the resolution.

**Comment by notatallshaw** [comment]
Thanks for the update, I will compare to Pip with  --only-binary :all: from now on.

**Comment by wolfv** [comment]
If you have hints on how we can make sdists work we would also gladly take them (#32)

**Comment by baszalmstra** [comment]
Im going to close this issue in favor of #32
