### ISSUE TITLE
Rip doesn't seem to get correct Python version from venv environment

### ISSUE THREAD

**Issue by notatallshaw** [prefix-dev/rip#34]
Today I was testing a backtracking problem with Pip on Windows Python 3.8, so I thought I would compare it against rip. 

I did the following:

```
> py -3.8 -m venv .venv
> .venv\Scripts\activate
(.venv) > python -V
Python 3.8.10
(.venv) > cargo r -- "scipy>=1.4.0"
    Finished dev [unoptimized + debuginfo] target(s) in 0.29s
     Running `target\debug\rip.exe scipy>=1.4.0`
Resolved environment:
- scipy >= 1.4.0

Name   Version
numpy  1.26.0
scipy  1.11.3
```

Problem is these versions of scipy and numpy don't support Python 3.8

**Comment by baszalmstra** [comment]
We dont support environment markers besides extras yet. See: https://github.com/prefix-dev/rip/issues/2

**Comment by notatallshaw** [comment]
Gotcha, I'll follow that issue and retest once implemented.
