### ISSUE TITLE
Refactor `Specifier` to use `resolvo::range::Range`

### ISSUE THREAD

**Issue by baszalmstra** [prefix-dev/rip#40]
The `Specifier` struct uses a custom implementation to create a range. Instead of returning half-open-ranges, it would be nicer to return a [`resolvo::range::Range`](https://docs.rs/resolvo/latest/resolvo/range/struct.Range.html#)

This does mean that the resolvo feature should also be enabled.. Should we get rid of the feature and always include resolvo then? Or should we move the `Range` struct into a separate crate?

**Comment by wolfv** [comment]
IMO resolvo seems like a core piece of `rip` so we could always enable it. We could rather factor out lower level parts of `rip` into other crates (what konstin is already doing with `pep440_rs` and `pep558_rs` etc.

WDYT?

**Comment by baszalmstra** [comment]
I agree! Im working on integrating pep508_rs and then this becomes obsolete.
