### ISSUE TITLE
Support freezing requirements files?

### ISSUE THREAD

**Issue by AustinScola** [prefix-dev/rip#55]
I would love to see support for freezing requirements files!

I currently use [pip-tools](https://pypi.org/project/pip-tools/) compile to freeze a large number of requirements files but it is so slow.

**Comment by baszalmstra** [comment]
This is most likely something we can add if and when we flesh out the binary. However, the primary goal of this library is to serve as a library for other tools to consume. But I would happily accept a PR!

**Comment by tdejager** [comment]
Closing this because it's currently not in scope
