### ISSUE TITLE
Feat: Install wheel in an existing environment

### ISSUE THREAD

**Issue by tdejager** [prefix-dev/rip#6]
Install a `.wheel` file in an existing enviroment. Essentially, specify a location in which you want to unpack the wheel contents.

--- 

Some support for unpacking wheels has landed but there are still a bunch of open issues that require attention.

- [x] #51 
- [x] #53 
- [x] #58
- [x] #59
- [x] #60
- [x] #61
- [x] #62
- [x] #63
- [x] #64

**Comment by baszalmstra** [comment]
Some support for unpacking/installing wheels has landed in #51 #53 but support for some crucial features is still missing:

In no particular order:

- [ ] Parse entry_points.txt and create script wrappers
- [ ] Rewrite #!python.
- [ ] Bytecode compilation
- [ ] Add `REQUESTED` file (<https://peps.python.org/pep-0376/#requested>)
- [ ] Add `direct_url.json` file (<https://peps.python.org/pep-0610/>)
- [ ] Support additional missing installation categories (e.g. `headers`)

**Comment by tdejager** [comment]
Closing this because separate issues exist.
