### ISSUE TITLE
Add `REQUESTED` file

### ISSUE THREAD

**Issue by baszalmstra** [prefix-dev/rip#61]
See https://peps.python.org/pep-0376/#requested

I think we should add this to the `UnpackWheelOptions`.

**Comment by tdejager** [comment]
Closing this for now because of PyPa packaging standards:

> The previous versions of this specification also specified a REQUESTED file. This file is now considered a tool-specific extension, but may be standardized again in the future. See [PEP 376](https://www.python.org/dev/peps/pep-0376/#requested) for its original meaning.

Let's include it if we see a need for it :)
