### ISSUE TITLE
Feat: Determine the packages installed in an environment

### ISSUE THREAD

**Issue by tdejager** [prefix-dev/rip#7]
We need to determine what packages are installed into an environment, so that we can actually mark these as `favored` when using the solver.

When a certain directory is selected determine if and what package(s) is/are installed. Maybe take a look how pip/poetry are doing this.

**Comment by shughes-uk** [comment]
It's more of an art than a science when you have a mixed pip/conda environment!

**Comment by baszalmstra** [comment]
@shughes-uk it looks like conda packages of python packages have an INSTALLER file that contains conda. Do you know if this is always the case?

**Comment by wolfv** [comment]
even if they don't, with rattler/mamba we could potentially force this, right? I think some really old packages might not have the right value.

The other option would be to compare with the entries of `conda-meta` (although pip might still have overwritten the contents of the site-packages folder after it was installed with conda).

**Comment by shughes-uk** [comment]
Tips off the top of my head

- The `INSTALLER` file is usually around, but usually missing from egg packages (lots of these on conda-forge)
- Fetch hashes for package files that are listed in `conda-meta`, compare with the hash of actually "active" files, not sure there's a better way to figure out what's actually installed.
- Multiple `dist-info` files for a one package is actually not uncommon, probably from people killing `pip` during an install or conda shenanigans
- `egg-link` still pops up
- `.pth` files pointing to editable installs can exist alongside the non-editable normal install, they just take precedence.
- There's a few older versions of poetry that generate valid but bad `direct_urls.json` if you want to look at that, i forget the issue number where they fix it.

**Comment by wolfv** [comment]
Uh oh, we don't deal with `egg` files as of now :D Are they really still around?! We also currently deal with source distributions, but that's kinda high up on the list as it seems very much required for a bunch of real-world resolves.
Thanks for your insights!

**Comment by baszalmstra** [comment]
@tdejager should we close this issue and open new ones if we encounter problems?

**Comment by wolfv** [comment]
@baszalmstra / @tdejager as far as I understand we do have code for this, right?

**Comment by baszalmstra** [comment]
Yeah we do! We can close this. There are probably edge cases but lets file new reports for those.
