### ISSUE TITLE
Allow creation of virual env and installing of wheel files into this env.

### ISSUE THREAD

**Issue by tdejager** [prefix-dev/rip#78]
We need this mainly because of #32.

When we are building sdist we need create a build environment isolated from the system but using the current system interpreter so that we can build the source dist in this environment.

I'm already working on this in https://github.com/tdejager/rip/tree/feat/venv-creation. In which I'm planning to:

- [x] Create venv using `python -m venv --no-pip`
- [x] Get the correct install paths for this venv, need #77 for this
- [x] Be able to install `.whl` into this venv
- [x] Create a small test that executes a python thing in there 

Currently, I want to do this with just with `python -m venv` but if we have the system intepreter we can create an environment without executing python if we want later on see: https://packaging.python.org/en/latest/specifications/virtual-environments/#declaring-installation-environments-as-python-virtual-environments.

Edit:

Currently ticking this off in: https://github.com/prefix-dev/rip/pull/82

**Comment by cnpryer** [comment]
> Create a small test that executes a python thing in there

Have you thought about how you'd want to test something like this?

**Comment by tdejager** [comment]
> > Create a small test that executes a python thing in there
> 
> Have you thought about how you'd want to test something like this?

I actually have a simple test in this PR: https://github.com/prefix-dev/rip/pull/82

**Comment by tdejager** [comment]
Closing this we can re-open if we need more specific functionality.
