### ISSUE TITLE
Create venv purely from Rust

### ISSUE THREAD

**Issue by tdejager** [prefix-dev/rip#83]
>FWIW, if you want to avoid the overhead of a subprocess call here, it's not particularly difficult to implement the logic for creating a virtual environment, especially given that you don't want to have any packages installed within it: https://peps.python.org/pep-0405/#creating-virtual-environments has the details (you don't really need activation files for your use case IIUC).

_Originally posted by @pradyunsg in https://github.com/prefix-dev/rip/pull/82#discussion_r1397137533_

We can modify the `venv` module to be able to do this just from rust, and link the system intepreter into the virtual env.

**Comment by nichmor** [comment]
Hi there! 
I'm interested in tackling this issue. 
Would it be possible for me to start working on it? 
I've checked that it's not assigned to anyone, but I wanted to double-check with you.

Thank you!

**Comment by tdejager** [comment]
Pleas go ahead! If you need any pointers let me know! I'm happy that you are willing to do this ☺️
